# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_time', models.DateTimeField()),
            ],
        ),
    ]
