# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charged_duration', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('price', models.CharField(max_length=1000)),
                ('time_stamp', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
                ('vehicle_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.VehicleIn')),
            ],
        ),
        migrations.CreateModel(
            name='BillingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.FloatField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField()),
                ('time_stamp', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingRecord')),
            ],
        ),
        migrations.CreateModel(
            name='OfflinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15)),
                ('parking_card_number', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('payment_type', models.CharField(choices=[('PY', 'payment for parking time'), ('TO', 'payment for not leaving on time')], default='PY', max_length=2)),
                ('payment_time', models.DateTimeField()),
                ('time_stamp', models.DateTimeField()),
                ('notice_id', models.IntegerField(default=0)),
                ('price_list', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField()),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingLot')),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField()),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingRecord')),
            ],
        ),
        migrations.CreateModel(
            name='PrePayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=32)),
                ('mch_id', models.CharField(max_length=32)),
                ('trade_no', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_channel', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
