# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayorder',
            name='open_id',
            field=models.CharField(default='001', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepayorder',
            name='prepay_id',
            field=models.CharField(default='001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepayorder',
            name='time_end',
            field=models.CharField(default='2016-02-21 03:11:52', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prepayorder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prepayorder',
            name='transaction_id',
            field=models.CharField(max_length=32),
        ),
    ]
