# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20160321_2022'),
        ('billing', '0006_auto_20160321_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15)),
                ('parking_card_number', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('payment_time', models.CharField(max_length=25)),
                ('end_time', models.CharField(max_length=25)),
                ('time_stamp', models.BigIntegerField(default=0)),
                ('notice_id', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField()),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingLot')),
            ],
        ),
    ]
