# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_monthlycardpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinepayment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='payment_time',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='time_stamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
