# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0005_roadsideparkingregister'),
        ('billing', '0008_auto_20160415_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charged_duration', models.IntegerField(default=0)),
                ('out_trade_no', models.CharField(max_length=50)),
                ('spbill_create_ip', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_channel', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.VehicleIn')),
            ],
        ),
        migrations.CreateModel(
            name='BillNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('spbill_pay_ip', models.CharField(max_length=50)),
                ('trade_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='vehicle_in',
        ),
        migrations.RemoveField(
            model_name='billingstatus',
            name='account',
        ),
        migrations.RemoveField(
            model_name='billingstatus',
            name='record',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_record',
        ),
        migrations.DeleteModel(
            name='BillingRecord',
        ),
        migrations.DeleteModel(
            name='BillingStatus',
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='billing.Bill'),
            preserve_default=False,
        ),
    ]
