# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20160510_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycardpayment',
            name='notice_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='notice_id',
            field=models.CharField(max_length=40),
        ),
    ]
