# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20160611_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_channel',
            field=models.CharField(max_length=20),
        ),
    ]
